// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es/el-avatar')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElCard: typeof import('element-plus/es/el-card')['default']
    ElCol: typeof import('element-plus/es/el-col')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElHeader: typeof import('element-plus/es/el-header')['default']
    ElImage: typeof import('element-plus/es/el-image')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElRow: typeof import('element-plus/es/el-row')['default']
    ElTag: typeof import('element-plus/es/el-tag')['default']
    ElTimeline: typeof import('element-plus/es/el-timeline')['default']
    ElTimelineItem: typeof import('element-plus/es/el-timeline-item')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
