apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: laq-front
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: laq-front
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: laq-front
    spec:
      # 定义容器，可以多个
      containers:
      - name: laq-front # 容器名字
        image: ccr.ccs.tencentyun.com/lin-and-qi/laq-front:latest # 镜像
